package io.github.jbarr21.kotlin.strava.model

import com.squareup.moshi.JsonClass
import java.time.Instant
import java.time.format.DateTimeFormatter

@JsonClass(generateAdapter = true)
data class Activity(
  val achievement_count: Int,
  val athlete: AthleteId,
  val athlete_count: Int,
  val average_cadence: Double?,
  val average_heartrate: Double?,
  val average_speed: MetersPerSec,
  val average_temp: Double?,
  val average_watts: Double?,
  val comment_count: Int,
  val commute: Boolean,
  val device_watts: Boolean?,
  val display_hide_heartrate_option: Boolean,
  val distance: Meters,
  val elapsed_time: Seconds,
  val elev_high: Meters?,
  val elev_low: Meters?,
  val end_latlng: List<Double>?,
  val external_id: String?,
  val flagged: Boolean,
  val from_accepted_tag: Boolean?,
  val gear_id: String?,
  val has_heartrate: Boolean,
  val has_kudoed: Boolean,
  val heartrate_opt_out: Boolean,
  val id: Long,
  val kilojoules: Double?,
  val kudos_count: Int,
  val location_city: String?,
  val location_country: String?,
  val location_state: String?,
  val manual: Boolean,
  val map: Map,
  val max_heartrate: Double?,
  val max_speed: Double,
  val moving_time: Seconds,
  val name: String,
  val photo_count: Int,
  val pr_count: Int,
  val private: Boolean,
  val resource_state: Long,
  val start_date: String,
  val start_date_local: String,
  val start_latitude: Double?,
  val start_latlng: List<Double>?,
  val start_longitude: Double?,
  val suffer_score: Double?,
  val timezone: String,
  val total_elevation_gain: Meters,
  val total_photo_count: Int,
  val trainer: Boolean,
  val type: String,
  val upload_id: Long?,
  val upload_id_str: String?,
  val utc_offset: Long,
  val visibility: String,
  val workout_type: Int?
) {
  val timestampUtc = Instant.from(DateTimeFormatter.ISO_DATE_TIME.parse(start_date)).epochSecond
}
